services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_passwort
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_passwort
      MYSQL_ROOT_PASSWORD: root_passwort
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  wordpress_data:
  db_data:
